<?php
/**
 * @author Vlad Patru
 */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->getApiKey()) { ?>
    <script
        type="module"
        src="https://cdn.what3words.com/javascript-components@4.2.2/dist/what3words/what3words.esm.js">
    </script>
    <script
        nomodule
        src="https://cdn.what3words.com/javascript-components@4.2.2/dist/what3words/what3words.js">
    </script>
    <script>
        window.w3wConfig = <?= /* @noEscape */ $viewModel->getSerializedConfig() ?>;
    </script>
    <?php if($viewModel->getShowTooltip()){ ?>
        <style>
            body .page-wrapper .main what3words-autosuggest
            > .what3words-autosuggest
            > .what3words-autosuggest-input-wrapper
            > .what3words-autosuggest-state {
                right: 40px;
            }
        </style>
    <?php }; ?>
<?php } ?>

