<?php
/**
 * What3Words_What3Words
 *
 * @category    WorkInProgress
 * @copyright   Copyright (c) 2020 What3Words
 * @author      Vlad Patru <vlad@wearewip.com>
 * @link        http://www.what3words.com
 */

/** @var \Magento\Customer\Block\Address\Edit $block */
$viewModel = $block->getViewModel();

use Magento\Customer\Block\Widget\Company;
use Magento\Customer\Block\Widget\Fax;
use Magento\Customer\Block\Widget\Telephone;

$_company = $block->getLayout()->createBlock(Company::class);
$_telephone = $block->getLayout()->createBlock(Telephone::class);
$_fax = $block->getLayout()->createBlock(Fax::class) ?>
<form class="form-address-edit"
      action="<?= $block->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Contact Information')) ?></span></legend>
        <br>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <?= $block->getNameBlockHtml() ?>

        <?php if ($_company->isEnabled()): ?>
            <?= $_company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
        <?php endif ?>

        <?php if ($_telephone->isEnabled()): ?>
            <?= $_telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
        <?php endif ?>

        <?php if ($_fax->isEnabled()): ?>
            <?= $_fax->setFax($block->getAddress()->getFax())->toHtml() ?>
        <?php endif ?>

    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Address')) ?></span></legend>
        <br>
        <?php $_streetValidationClass = $viewModel->getAddressHelper()->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <label for="street_1" class="label">
                <span><?= /* @noEscape */
                    $block->getAttributeData()->getFrontendLabel('street') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="street[]"
                       value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= /* @noEscape */
                        $block->getAttributeData()->getFrontendLabel('street') ?>"
                       id="street_1"
                       class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"/>
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $viewModel->getAddressHelper()->getStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= /* @noEscape */
                            $_i + 1 ?>">
                                <span><?= $block->escapeHtml(__('Street Address %1', $_i + 1)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]"
                                       value="<?= $block->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                                       title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                                       id="street_<?= /* @noEscape */
                                        $_i + 1 ?>"
                                       class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php if ($viewModel->getAddressHelper()->isVatAttributeVisible()): ?>
            <div class="field taxvat">
                <label class="label" for="vat_id">
                    <span><?= /* @noEscape */
                        $block->getAttributeData()->getFrontendLabel('vat_id') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="vat_id"
                           value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                           title="<?= /* @noEscape */$block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                           class="input-text <?= $block->escapeHtmlAttr($viewModel->getAddressHelper()->getAttributeValidationClass('vat_id')) ?>"
                           id="vat_id">
                </div>
            </div>
        <?php endif; ?>
        <div class="field city required">
            <label class="label" for="city"><span><?= /* @noEscape */
                    $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
            <div class="control">
                <input type="text"
                       name="city"
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                       class="input-text <?= $block->escapeHtmlAttr($viewModel->getAddressHelper()->getAttributeValidationClass('city')) ?>"
                       id="city">
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id">
                <span><?= /* @noEscape */
                    $block->getAttributeData()->getFrontendLabel('region') ?></span>
            </label>
            <div class="control">
                <select id="region_id" name="region_id"
                        title="<?= /* @noEscape */
                        $block->getAttributeData()->getFrontendLabel('region') ?>"
                        class="validate-select region_id" <?= /* @noEscape */
                        !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>>
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text"
                       id="region"
                       name="region"
                       value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"
                       title="<?= /* @noEscape */
                        $block->getAttributeData()->getFrontendLabel('region') ?>"
                       class="input-text validate-not-number-first <?= $block->escapeHtmlAttr($viewModel->getAddressHelper()->getAttributeValidationClass('region')) ?>"<?= !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>/>
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip">
                <span><?= /* @noEscape */
                    $block->getAttributeData()->getFrontendLabel('postcode') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="postcode"
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                       title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                       id="zip"
                       class="input-text validate-zip-international <?= $block->escapeHtmlAttr($viewModel->getAddressHelper()->getAttributeValidationClass('postcode')) ?>">
                <div role="alert" class="message warning" style="display:none">
                    <span></span>
                </div>
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?= /* @noEscape */
                    $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
            <div class="control">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>
        <?php $apiKey = $viewModel->getApiKey();
            $tooltipClass = $viewModel->getShowTooltip() ? '_with-tooltip' : '';
            $w3wAddress = $block->escapeHtmlAttr($block->getAddress()->getCustomAttribute('w3w') ? $block->getAddress()->getCustomAttribute('w3w')->getValue() : '');
            $fieldLabel = $viewModel->getOverrideLabel() ? $viewModel->getCustomLabel() : __('what3words address');
            $invalidError = $viewModel->getInvalidMessage() ? 'invalid_address_error_message="'. $viewModel->getInvalidMessage() .'"' : '';
            $rtlDir = $viewModel->getRtlDir() ? 'dir="rtl"' : '';
            $autocompleteLang = $viewModel->getLang() ? 'language="'. $viewModel->getLang(). '"' : '';
        if (isset($apiKey)) { ?>
            <div class="field w3w">
                <label class="label" for="w3w">
                    <span><?= /* @noEscape */ $fieldLabel ?></span>
                </label>
                <div class="control <?= /** @noEscape  */ $tooltipClass;?>">
                    <div class="input-wrap-w3w">
                        <what3words-autosuggest
                            api_key="<?= /** @noEscape  */ $viewModel->getApiKey(); ?>"
                            headers='{"X-W3W-Plugin": "what3words-Magento/<?=  /* @noEscape */ $viewModel->getConfig()['w3w_version'];?> ({Magento_version: <?= /* @noEscape */ $viewModel->getMagentoVersion();?> , Location: Account})"}'
                            id="autosuggest-w3w"  validation="true"
                            variant="inherit"
                            <?= /* @noEscape */ $invalidError; ?>
                            <?= /* @noEscape */ $rtlDir; ?>
                            <?= /* @noEscape */ $autocompleteLang; ?>>
                            <input
                                class="input-text what3words-autosuggest"
                                placeholder="<?= /* @noEscape */ $viewModel->getPlaceholder(); ?>"
                                type="text"
                                name="w3w"
                                id="what3words"
                                data-mage-init='{"w3wAutocomplete":{}}'
                                <?= /* @noEscape */ $rtlDir; ?>
                                value="<?= /* @noEscape */ $w3wAddress; ?>"
                                title="<?= /* @noEscape */ $fieldLabel ?>"
                            optional
                            />
                        </what3words-autosuggest>

                    </div>

                    <?php if ($viewModel->getShowTooltip()): ?>
                        <div class="field-tooltip toggle w3w-tooltip">
                            <div class="tooltip wrapper">
                                <span class="tooltip toggle field-tooltip-action"></span>
                                <div class="tooltip content">
                                    <?= /* @noEscape */ $viewModel->getTooltipText(); ?>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>

                    <div class="hidden-inputs">
                        <?php
                        $w3wNearest = $block->escapeHtmlAttr($block->getAddress()->getCustomAttribute('w3w_nearest') ? $block->getAddress()->getCustomAttribute('w3w_nearest')->getValue() : '');
                        $w3wCoords = $block->escapeHtmlAttr($block->getAddress()->getCustomAttribute('w3w_coordinates') ? $block->getAddress()->getCustomAttribute('w3w_coordinates')->getValue() : '');
                        ?>
                        <input type="hidden" name="w3w_nearest"
                               value="<?= /* @noEscape */ $w3wNearest; ?>"
                               title="<?= /* @noEscape */ $w3wNearest; ?>"
                               class="input-text <?= /* @noEscape */ $w3wNearest; ?> hidden" id="w3w_nearest">
                        <input type="hidden" name="w3w_coordinates"
                               value="<?= /* @noEscape */ $w3wCoords; ?>"
                               title="<?= /* @noEscape */ $w3wCoords; ?>"
                               class="input-text <?= /* @noEscape */ $w3wCoords; ?> hidden" id="w3w_coordinates">
                    </div>
                </div>
            </div>

        <?php } ?>

        <?php if ($block->isDefaultBilling()): ?>
            <div class="message info">
                <span><?= $block->escapeHtml(__("It's a default billing address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultBilling()): ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
                <label class="label" for="primary_billing">
                    <span><?= $block->escapeHtml(__('Use as my default billing address')) ?></span>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_billing" value="1"/>
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()): ?>
            <div class="message info">
                <span><?= $block->escapeHtml(__("It's a default shipping address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultShipping()): ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
                <label class="label" for="primary_shipping">
                    <span><?= $block->escapeHtml(__('Use as my default shipping address')) ?></span>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_shipping" value="1">
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    data-action="save-address"
                    title="<?= $block->escapeHtmlAttr(__('Save Address')) ?>">
                <span><?= $block->escapeHtml(__('Save Address')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */
                $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $viewModel->getDirHelper()->getRegionJson() ?>,
                "defaultRegion": "<?= (int)$block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $viewModel->getDirHelper()->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
