<?php
/**
 * @var $block \What3Words\What3Words\Block\Customer\Address
 */

$what3words = $block->get3WordAddress();
if ($block->getIsEnabled()) : ?>
    <script type="text/html" id="what3words-customer-address">
        <div class="field what3words" id="what3words-customer-field" data-bind="scope: 'what3words-address'">
            <label class="label" for="what3words"><span><?php /* @escapeNotVerified */ echo __('3 word address') ?></span></label>
            <div class="control w3w-control">
                <input type="text" name="what3words"
                       value="<?php echo $block->get3WordAddress() ?
                           __($block->get3WordAddress()) :
                           __(''); ?>"
                       title="<?php /* @escapeNotVerified */ echo __('3 word address') ?>"
                       data-validate="{'w3w_valid':true}"
                       id="what3words" class="input-text validate-what3words"/>
                <div class="field-tooltip w3w-tooltip">
                    <span class="what3words-tooltip tooltip-toggle field-tooltip-action action-help" data-toggle="dropdown"></span>
                    <span class="what3words-tooltip-content tooltip-content field-tooltip-content">
                    <?php echo __('By entering your 3 word address you make it much
                    easier for our delivery partners to find you first time.
                    To discover your 3 word address, visit '); ?>
                        <a href="https://map.what3words.com" target="_blank">what3words.com</a>
                </span>
                </div>
            </div>
        </div>
    </script>

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "what3words-address": {
                            "component": "What3Words_What3Words/js/view/customer/edit",
                            "apiKey": "<?php echo $block->getApiKey(); ?>",
                            "validateUrl": "<?php echo $block->getValidateUrl(); ?>",
                            "resultCount": "<?php echo $block->getResultCount(); ?>",
                            "typeaheadDelay": "<?php echo $block->getTypeaheadDelay(); ?>",
                            "placeholder": "<?php echo $block->getPlaceholder(); ?>",
                            "allowedCountries": <?php echo $block->getAllowedCountries(); ?>

                        }
                    }
                }
            }
        }
    </script>
<?php endif; ?>
