<?php
/**
 * @var $block What3Words\What3Words\Block\Adminhtml\Sales\Address\Edit
 * Initialise a JS component to handle loading the saved address
 */
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "what3words-order-address": {
                            "component": "What3Words_What3Words/js/view/admin/sales/address/edit",
                            "w3w": "<?php echo $block->getW3wFromOrder(); ?>"
                        }
                    }
                }
            }
        }
    </script>
